version: "3"

services:
    postgreshost:
        image: 'postgres:16-alpine'
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Welcome!
            - POSTGRES_DB=user

    rabbitmqhost:
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"

    banking-service:
        build:
            context: ./banking-service
            dockerfile: ./Dockerfile
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Welcome!
            - POSTGRES_HOST=postgreshost
            - POSTGRES_DB=user
        ports:
            - "8000:8000"
        depends_on:
            - postgreshost

    statement-generation-service:
        build:
            context: ./statement-generation-service
            dockerfile: ./Dockerfile
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Welcome!
            - POSTGRES_HOST=postgreshost
            - POSTGRES_DB=user
        ports:
            - "8001:8001"
        depends_on:
            - postgreshost

    statement-worker:
        build: ./monthly_statements
        command: celery -A monthly_statements worker -l debug
        volumes:
            - ./:/app
        depends_on:
            - rabbitmqhost
            - postgreshost
            - statement-generation-service
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Welcome!
            - POSTGRES_HOST=postgreshost
            - POSTGRES_DB=user
            - CELERY_BROKER_URL=pyamqp://guest@rabbitmqhost:5672//

    statement-scheduler:
        build: ./monthly_statements
        command: celery -A monthly_statements beat -l debug
        volumes:
            - ./:/app
        depends_on:
            - rabbitmqhost
            - postgreshost
            - statement-worker
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Welcome!
            - POSTGRES_HOST=postgreshost
            - POSTGRES_DB=user
            - CELERY_BROKER_URL=pyamqp://guest@rabbitmqhost:5672//

volumes:
    postgres_data:
